[colors]
cursor = {cursor = "#B4E1FD" }
[colors.primary]
foreground = "#B4E1FD"
background = "#0D1926"
[colors.normal]
black = "#363636"
red = "#FF0883"
green = "#83FF08"
yellow = "#FF8308"
blue = "#0883FF"
magenta = "#8308FF"
cyan = "#08FF83"
white = "#B6B6B6"
[colors.bright]
black = "#424242"
red = "#FF1E8E"
green = "#8EFF1E"
yellow = "#FF8E1E"
blue = "#1E8EFF"
magenta = "#8E1EFF"
cyan = "#1EFF8E"
white = "#C2C2C2"
