[colors]
cursor = {cursor = "#898EA4" }
[colors.primary]
foreground = "#898EA4"
background = "#202746"
[colors.normal]
black = "#202746"
red = "#C94922"
green = "#AC9739"
yellow = "#C08B30"
blue = "#3D8FD1"
magenta = "#6679CC"
cyan = "#22A2C9"
white = "#979DB4"
[colors.bright]
black = "#6B7394"
red = "#C76B29"
green = "#AC9739"
yellow = "#C08B30"
blue = "#3D8FD1"
magenta = "#6679CC"
cyan = "#22A2C9"
white = "#F5F7FF"
    