[colors]
cursor = {cursor = "#9C9491" }
[colors.primary]
foreground = "#9C9491"
background = "#1B1918"
[colors.normal]
black = "#1B1918"
red = "#F22C40"
green = "#7B9726"
yellow = "#C38418"
blue = "#407EE7"
magenta = "#6666EA"
cyan = "#3D97B8"
white = "#A8A19F"
[colors.bright]
black = "#766E6B"
red = "#DF5320"
green = "#7B9726"
yellow = "#C38418"
blue = "#407EE7"
magenta = "#6666EA"
cyan = "#3D97B8"
white = "#F1EFEE"
