[colors]
cursor = {cursor = "#7195A8" }
[colors.primary]
foreground = "#7195A8"
background = "#161B1D"
[colors.normal]
black = "#161B1D"
red = "#D22D72"
green = "#568C3B"
yellow = "#8A8A0F"
blue = "#257FAD"
magenta = "#6B6BB8"
cyan = "#2D8F6F"
white = "#7EA2B4"
[colors.bright]
black = "#5A7B8C"
red = "#935C25"
green = "#568C3B"
yellow = "#8A8A0F"
blue = "#257FAD"
magenta = "#6B6BB8"
cyan = "#2D8F6F"
white = "#EBF8FF"
    