[colors]
cursor = {cursor = "#7E7887" }
[colors.primary]
foreground = "#7E7887"
background = "#19171C"
[colors.normal]
black = "#19171C"
red = "#BE4678"
green = "#2A9292"
yellow = "#A06E3B"
blue = "#576DDB"
magenta = "#955AE7"
cyan = "#398BC6"
white = "#8B8792"
[colors.bright]
black = "#655F6D"
red = "#AA573C"
green = "#2A9292"
yellow = "#A06E3B"
blue = "#576DDB"
magenta = "#955AE7"
cyan = "#398BC6"
white = "#EFECF4"
    