[colors]
cursor = {cursor = "#995900" }
[colors.primary]
foreground = "#9e999f"
background = "#222022"
[colors.normal]
black = "#222022"
red = "#8f6c93"
green = "#cc8c33"
yellow = "#ffd599"
blue = "#9a819c"
magenta = "#cc8c33"
cyan = "#cb79d2"
white = "#9e999f"
[colors.bright]
black = "#635f63"
red = "#d9b98c"
green = "#2f2d2f"
yellow = "#575158"
blue = "#6f6b70"
magenta = "#eaa8f0"
cyan = "#c38022"
white = "#fdebff"
