[colors]
cursor = {cursor = "#6f7285" }
[colors.primary]
foreground = "#98949e"
background = "#1e1d20"
[colors.normal]
black = "#1e1d20"
red = "#d53975"
green = "#6577ec"
yellow = "#a0acf8"
blue = "#af88f2"
magenta = "#d763e9"
cyan = "#8493f6"
white = "#eae8ed"
[colors.bright]
black = "#09070d"
red = "#eb75a2"
green = "#aeb8f9"
yellow = "#c6cdfb"
blue = "#ddcbfb"
magenta = "#e17ef1"
cyan = "#d6c2fa"
white = "#f7f6f9"
    