[colors]
cursor = {cursor = "#6d8884" }
[colors.primary]
foreground = "#8995a9"
background = "#1a1d23"
[colors.normal]
black = "#1a1d23"
red = "#a24ad9"
green = "#0d9c89"
yellow = "#1ed2ba"
blue = "#74a8fb"
magenta = "#9488f2"
cyan = "#1bbba6"
white = "#e7eaee"
[colors.bright]
black = "#07090d"
red = "#c27eed"
green = "#2fdac3"
yellow = "#93ece0"
blue = "#c7dcff"
magenta = "#aba1f7"
cyan = "#c2d9ff"
white = "#f6f7f9"
