[colors]
cursor = {cursor = "#797481" }
[colors.primary]
foreground = "#9d949e"
background = "#201d20"
[colors.normal]
black = "#201d20"
red = "#ce672c"
green = "#9263e3"
yellow = "#b792f6"
blue = "#db75eb"
magenta = "#e96396"
cyan = "#a57af0"
white = "#ede8ed"
[colors.bright]
black = "#0c070d"
red = "#e78b55"
green = "#c0a1f7"
yellow = "#d6c2fa"
blue = "#f1c3f8"
magenta = "#f17eaa"
cyan = "#edb1f6"
white = "#f8f6f9"
