[colors]
cursor = {cursor = "#817479" }
[colors.primary]
foreground = "#a39b8f"
background = "#221f1c"
[colors.normal]
black = "#221f1c"
red = "#5c6feb"
green = "#dd407c"
yellow = "#f17eaa"
blue = "#e6971a"
magenta = "#1bbba6"
cyan = "#e96396"
white = "#eeebe8"
[colors.bright]
black = "#0d0b07"
red = "#929ff7"
green = "#f391b6"
yellow = "#f6b1cc"
blue = "#f5d8a8"
magenta = "#1ed2ba"
cyan = "#f3cd91"
white = "#f9f8f6"
    