[colors]
cursor = {cursor = "#67768e" }
[colors.primary]
foreground = "#95949e"
background = "#1d1d20"
[colors.normal]
black = "#1d1d20"
red = "#d4359a"
green = "#4287f5"
yellow = "#88b4fc"
blue = "#a095f3"
magenta = "#ba6cea"
cyan = "#659efb"
white = "#e9e8ed"
[colors.bright]
black = "#08070d"
red = "#eb75c0"
green = "#9cc1fc"
yellow = "#c2d9ff"
blue = "#d9d5fc"
magenta = "#c988f2"
cyan = "#d1cbfb"
white = "#f6f6f9"
    