[colors]
cursor = {cursor = "#45373C" }
[colors.primary]
foreground = "#45373C"
background = "#D5CCBA"
[colors.normal]
black = "#20111B"
red = "#BE100E"
green = "#858162"
yellow = "#EAA549"
blue = "#426A79"
magenta = "#97522C"
cyan = "#989A9C"
white = "#968C83"
[colors.bright]
black = "#5E5252"
red = "#BE100E"
green = "#858162"
yellow = "#EAA549"
blue = "#426A79"
magenta = "#97522C"
cyan = "#989A9C"
white = "#D5CCBA"
