[colors]
cursor = {cursor = "#7869C4" }
[colors.primary]
foreground = "#7869C4"
background = "#40318D"
[colors.normal]
black = "#090300"
red = "#883932"
green = "#55A049"
yellow = "#BFCE72"
blue = "#40318D"
magenta = "#8B3F96"
cyan = "#67B6BD"
white = "#FFFFFF"
[colors.bright]
black = "#000000"
red = "#883932"
green = "#55A049"
yellow = "#BFCE72"
blue = "#40318D"
magenta = "#8B3F96"
cyan = "#67B6BD"
white = "#F7F7F7"
