[colors]
cursor = {cursor = "#D4D4D4" }
[colors.primary]
foreground = "#D4D4D4"
background = "#2D2D2D"
[colors.normal]
black = "#646464"
red = "#F58E8E"
green = "#A9D3AB"
yellow = "#FED37E"
blue = "#7AABD4"
magenta = "#D6ADD5"
cyan = "#79D4D5"
white = "#D4D4D4"
[colors.bright]
black = "#646464"
red = "#F58E8E"
green = "#A9D3AB"
yellow = "#FED37E"
blue = "#7AABD4"
magenta = "#D6ADD5"
cyan = "#79D4D5"
white = "#D4D4D4"
