[colors]
cursor = {cursor = "#B9BCBA" }
[colors.primary]
foreground = "#B9BCBA"
background = "#1F1F1F"
[colors.normal]
black = "#3A3D43"
red = "#BE3F48"
green = "#879A3B"
yellow = "#C5A635"
blue = "#4F76A1"
magenta = "#855C8D"
cyan = "#578FA4"
white = "#B9BCBA"
[colors.bright]
black = "#888987"
red = "#FB001F"
green = "#0F722F"
yellow = "#C47033"
blue = "#186DE3"
magenta = "#FB0067"
cyan = "#2E706D"
white = "#FDFFB9"
    