[colors]
cursor = {cursor = "#FFFFFF" }
[colors.primary]
foreground = "#FFFFFF"
background = "#272A34"
[colors.normal]
black = "#1F2229"
red = "#D41919"
green = "#5EBDAB"
yellow = "#FEA44C"
blue = "#367BF0"
magenta = "#BF2E5D"
cyan = "#49AEE6"
white = "#E6E6E6"
[colors.bright]
black = "#8C42AB"
red = "#EC0101"
green = "#47D4B9"
yellow = "#FF8A18"
blue = "#277FFF"
magenta = "#D71655"
cyan = "#05A1F7"
white = "#FFFFFF"
