[colors]
cursor = {cursor = "#D7D7DB" }
[colors.primary]
foreground = "#D7D7DB"
background = "#2A2A2E"
[colors.normal]
black = "#2A2A2E"
red = "#B98EFF"
green = "#FF7DE9"
yellow = "#729FCF"
blue = "#66A05B"
magenta = "#75507B"
cyan = "#ACACAE"
white = "#FFFFFF"
[colors.bright]
black = "#A40000"
red = "#BF4040"
green = "#66A05B"
yellow = "#FFB86C"
blue = "#729FCF"
magenta = "#8F5902"
cyan = "#C4A000"
white = "#5C3566"
