[colors]
cursor = {cursor = "#FFFFFF" }
[colors.primary]
foreground = "#FFFFFF"
background = "#1D2837"
[colors.normal]
black = "#000000"
red = "#F9555F"
green = "#21B089"
yellow = "#FEF02A"
blue = "#589DF6"
magenta = "#944D95"
cyan = "#1F9EE7"
white = "#BBBBBB"
[colors.bright]
black = "#555555"
red = "#FA8C8F"
green = "#35BB9A"
yellow = "#FFFF55"
blue = "#589DF6"
magenta = "#E75699"
cyan = "#3979BC"
white = "#FFFFFF"
    