[colors]
cursor = {cursor = "#A0A0A0" }
[colors.primary]
foreground = "#A0A0A0"
background = "#121212"
[colors.normal]
black = "#1B1D1E"
red = "#F92672"
green = "#A6E22E"
yellow = "#FD971F"
blue = "#66D9EF"
magenta = "#9E6FFE"
cyan = "#5E7175"
white = "#CCCCC6"
[colors.bright]
black = "#505354"
red = "#FF669D"
green = "#BEED5F"
yellow = "#E6DB74"
blue = "#66D9EF"
magenta = "#9E6FFE"
cyan = "#A3BABF"
white = "#F8F8F2"
    