[colors]
cursor = {cursor = "#DBDBDB" }
[colors.primary]
foreground = "#DBDBDB"
background = "#000000"
[colors.normal]
black = "#575757"
red = "#FF1B00"
green = "#A5E055"
yellow = "#FBE74A"
blue = "#496487"
magenta = "#FD5FF1"
cyan = "#86E9FE"
white = "#CBCCCB"
[colors.bright]
black = "#262626"
red = "#D51D00"
green = "#A5DF55"
yellow = "#FBE84A"
blue = "#89BEFF"
magenta = "#C001C1"
cyan = "#86EAFE"
white = "#DBDBDB"
    