[colors]
cursor = {cursor = "#29242A" }
[colors.primary]
foreground = "#29242A"
background = "#FEFAF9"
[colors.normal]
black = "#FEFAF9"
red = "#E14775"
green = "#269D69"
yellow = "#CC7A0A"
blue = "#E16032"
magenta = "#7058BE"
cyan = "#1C8CA8"
white = "#29242A"
[colors.bright]
black = "#6E6B6A"
red = "#E14775"
green = "#269D69"
yellow = "#CC7A0A"
blue = "#E16032"
magenta = "#7058BE"
cyan = "#1C8CA8"
white = "#29242A"
