[colors]
cursor = {cursor = "#FF3600" }
[colors.primary]
foreground = "#FF3600"
background = "#2B0C00"
[colors.normal]
black = "#401200"
red = "#FF3600"
green = "#FF3600"
yellow = "#FF3600"
blue = "#FF3600"
magenta = "#FF3600"
cyan = "#FF3600"
white = "#FF3600"
[colors.bright]
black = "#FF3600"
red = "#FF3600"
green = "#FF3600"
yellow = "#FF3600"
blue = "#FF3600"
magenta = "#FF3600"
cyan = "#FF3600"
white = "#FF3600"
