[colors]
cursor = {cursor = "#EAF2F1" }
[colors.primary]
foreground = "#EAF2F1"
background = "#3A3D4B"
[colors.normal]
black = "#3A3D4B"
red = "#FF657A"
green = "#BAD761"
yellow = "#FFD76D"
blue = "#FF9B5E"
magenta = "#C39AC9"
cyan = "#9CD1BB"
white = "#EAF2F1"
[colors.bright]
black = "#ADAEB4"
red = "#FF657A"
green = "#BAD761"
yellow = "#FFD76D"
blue = "#FF9B5E"
magenta = "#C39AC9"
cyan = "#9CD1BB"
white = "#EAF2F1"
