[colors]
cursor = {cursor = "#A0A0A0" }
[colors.primary]
foreground = "#A0A0A0"
background = "#222222"
[colors.normal]
black = "#383838"
red = "#A95551"
green = "#666666"
yellow = "#A98051"
blue = "#657D3E"
magenta = "#767676"
cyan = "#C9C9C9"
white = "#D0B8A3"
[colors.bright]
black = "#474747"
red = "#A97775"
green = "#8C8C8C"
yellow = "#A99175"
blue = "#98BD5E"
magenta = "#A3A3A3"
cyan = "#DCDCDC"
white = "#D8C8BB"
