[colors]
cursor = {cursor = "#D9E6F2" }
[colors.primary]
foreground = "#D9E6F2"
background = "#232E37"
[colors.normal]
black = "#0A0A0A"
red = "#AB8F74"
green = "#74AB8F"
yellow = "#8FAB74"
blue = "#8F74AB"
magenta = "#AB748F"
cyan = "#748FAB"
white = "#F2F2F2"
[colors.bright]
black = "#5D5D5D"
red = "#FF1D62"
green = "#9CC3AF"
yellow = "#FFD00A"
blue = "#AF9CC3"
magenta = "#FF1D62"
cyan = "#4BB8FD"
white = "#A020F0"
    