[colors]
cursor = {cursor = "#D4E7D4" }
[colors.primary]
foreground = "#D4E7D4"
background = "#243435"
[colors.normal]
black = "#757575"
red = "#825D4D"
green = "#728C62"
yellow = "#ADA16D"
blue = "#4D7B82"
magenta = "#8A7267"
cyan = "#729494"
white = "#E0E0E0"
[colors.bright]
black = "#8A8A8A"
red = "#CF937A"
green = "#98D9AA"
yellow = "#FAE79D"
blue = "#7AC3CF"
magenta = "#D6B2A1"
cyan = "#ADE0E0"
white = "#E0E0E0"
    