[colors]
cursor = {cursor = "#D0D0D0" }
[colors.primary]
foreground = "#D0D0D0"
background = "#262626"
[colors.normal]
black = "#1C1C1C"
red = "#D68686"
green = "#AED686"
yellow = "#D7AF87"
blue = "#86AED6"
magenta = "#D6AED6"
cyan = "#8ADBB4"
white = "#D0D0D0"
[colors.bright]
black = "#1C1C1C"
red = "#D68686"
green = "#AED686"
yellow = "#E4C9AF"
blue = "#86AED6"
magenta = "#D6AED6"
cyan = "#B1E7DD"
white = "#EFEFEF"
