[colors]
cursor = {cursor = "#868A8C" }
[colors.primary]
foreground = "#868A8C"
background = "#091116"
[colors.normal]
black = "#282A2E"
red = "#A54242"
green = "#A1B56C"
yellow = "#DE935F"
blue = "#225555"
magenta = "#85678F"
cyan = "#5E8D87"
white = "#777777"
[colors.bright]
black = "#373B41"
red = "#C63535"
green = "#608360"
yellow = "#FA805A"
blue = "#449DA1"
magenta = "#BA8BAF"
cyan = "#86C1B9"
white = "#C5C8C6"
