[colors]
cursor = {cursor = "#F8F8F8" }
[colors.primary]
foreground = "#F8F8F8"
background = "#1B1D1E"
[colors.normal]
black = "#1B1D1E"
red = "#F92672"
green = "#4DF840"
yellow = "#F4FD22"
blue = "#2757D6"
magenta = "#8C54FE"
cyan = "#38C8B5"
white = "#CCCCC6"
[colors.bright]
black = "#505354"
red = "#FF5995"
green = "#B6E354"
yellow = "#FEED6C"
blue = "#3F78FF"
magenta = "#9E6FFE"
cyan = "#23CFD5"
white = "#F8F8F2"
