[colors]
cursor = {cursor = "#FFFFFF" }
[colors.primary]
foreground = "#FFFFFF"
background = "#002451"
[colors.normal]
black = "#00346E"
red = "#FF9DA4"
green = "#D1F1A9"
yellow = "#FFEEAD"
blue = "#BBDAFF"
magenta = "#EBBBFF"
cyan = "#99FFFF"
white = "#FFFFFF"
[colors.bright]
black = "#7285B7"
red = "#FF9DA4"
green = "#D1F1A9"
yellow = "#FFEEAD"
blue = "#BBDAFF"
magenta = "#EBBBFF"
cyan = "#99FFFF"
white = "#FFFFFF"
    