[colors]
cursor = {cursor = "#C5C8C6" }
[colors.primary]
foreground = "#C5C8C6"
background = "#1D1F21"
[colors.normal]
black = "#282A2E"
red = "#CC6666"
green = "#B5BD68"
yellow = "#F0C674"
blue = "#81A2BE"
magenta = "#B294BB"
cyan = "#8ABEB7"
white = "#C5C8C6"
[colors.bright]
black = "#969896"
red = "#CC6666"
green = "#B5BD68"
yellow = "#F0C674"
blue = "#81A2BE"
magenta = "#B294BB"
cyan = "#8ABEB7"
white = "#FFFFFF"
    