[colors]
cursor = {cursor = "#877A9B" }
[colors.primary]
foreground = "#877A9B"
background = "#1B1B23"
[colors.normal]
black = "#000000"
red = "#B0425B"
green = "#37A415"
yellow = "#AD5C42"
blue = "#564D9B"
magenta = "#6C3CA1"
cyan = "#808080"
white = "#87799C"
[colors.bright]
black = "#5D3225"
red = "#FF6388"
green = "#29E620"
yellow = "#F08161"
blue = "#867AED"
magenta = "#A05EEE"
cyan = "#EAEAEA"
white = "#BFA3FF"
    