[colors]
cursor = {cursor = "#030093" }
[colors.primary]
foreground = "#424242"
background = "#FFFFEC"
[colors.normal]
black = "#424242"
red = "#B85C57"
green = "#57864E"
yellow = "#8F7634"
blue = "#2A8DC5"
magenta = "#8888C7"
cyan = "#6AA7A8"
white = "#FFFFEC"
[colors.bright]
black = "#999957"
red = "#E28C88"
green = "#7AB877"
yellow = "#9E9477"
blue = "#7EC6EB"
magenta = "#A9ABDA"
cyan = "#7AD0D1"
white = "#D6D687"
    