[colors]
cursor = {cursor = "#020202" }
[colors.primary]
foreground = "#020202"
background = "#F9F9F9"
[colors.normal]
black = "#020202"
red = "#CD3232"
green = "#00BC00"
yellow = "#A5A900"
blue = "#0752A8"
magenta = "#BC05BC"
cyan = "#0598BC"
white = "#343434"
[colors.bright]
black = "#5E5E5E"
red = "#CD3333"
green = "#1BCE1A"
yellow = "#ADBB5B"
blue = "#0752A8"
magenta = "#C451CE"
cyan = "#52A8C7"
white = "#A6A3A6"
    