[colors]
cursor = {cursor = "#999993" }
[colors.primary]
foreground = "#999993"
background = "#101010"
[colors.normal]
black = "#333333"
red = "#8C4665"
green = "#287373"
yellow = "#7C7C99"
blue = "#395573"
magenta = "#5E468C"
cyan = "#31658C"
white = "#899CA1"
[colors.bright]
black = "#3D3D3D"
red = "#BF4D80"
green = "#53A6A6"
yellow = "#9E9ECB"
blue = "#477AB3"
magenta = "#7E62B3"
cyan = "#6096BF"
white = "#C0C0C0"
    